services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=adm'
      - 'MYSQL_USER=adm'
      - 'MYSQL_PASSWORD=adm'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'
